### ISSUE TITLE
Import routines for Python 3.5 and higher are untested.

### ISSUE THREAD

**Issue by 1Reinier** [neurophysik/jitcdde#1]
Guess this must be on the roadmap already, but just putting it out there since many of us will use Python 3.5.

**Comment by Wrzlprmft** [comment]
Or I might as well remove the warning, since I saw it working on Python 3.5 (and just forgot about it). I also assume that it works for you since you saw the warning and didn’t report any further problems.

**Comment by 1Reinier** [comment]
Yeah it's working fine so far!
