### ISSUE TITLE
Problem trying the first example in mac os x

### ISSUE THREAD

**Issue by ajalvarez** [neurophysik/jitcdde#10]
I copy and paste the error/warning: 

```
Generating, compiling, and loading C code.
/Users/alejandro/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py:191: UserWarning: Traceback (most recent call last):
  File "/Users/alejandro/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py", line 189, in _attempt_compilation
    self.compile_C()
  File "/Users/alejandro/.local/lib/python3.6/site-packages/jitcdde/_jitcdde.py", line 515, in compile_C
    chunk_size = chunk_size, # only for OMP
  File "/Users/alejandro/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py", line 142, in _render_template
    codefile.write(template.render(kwargs))
UnicodeEncodeError: ascii codec can't encode character '\u201c' in position 2338: ordinal not in range(128)

  warn(format_exc())
/Users/alejandro/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py:193: UserWarning: 
============================================================
READ ME FIRST
============================================================
Generating compiled integrator failed; resorting to lambdified functions. If you can live with using the Python backend, you can call generate_lambdas to explicitly do this and bypass the compile attempt and error messages. Otherwise, you want to take care of fixing the above errors.
============================================================

============================================================

  warn(line + "READ ME FIRST" + line + "Generating compiled integrator failed; resorting to lambdified functions. If you can live with using the Python backend, you can call generate_lambdas to explicitly do this and bypass the compile attempt and error messages. Otherwise, you want to take care of fixing the above errors." + 2*line)
```

I suppose that I need to install an specific version/distribution of C.

**Comment by Wrzlprmft** [comment]
> UnicodeEncodeError: ascii codec can't encode character '\u201c' in position 2338: ordinal not in range(128)

Interestingly, it seems to be a problem with Jinja. Can remove line 128 from `jitced_template.c` and see whether this problem persists?

**Comment by Wrzlprmft** [comment]
Can you also please tell me your Jinja version (`import jinja2; print(jinja2.__version__`)? I guess that you might have fallen victim to [this issue](https://github.com/pallets/jinja/issues/309)?

**Comment by ajalvarez** [comment]
Hello,

First of all, your software is wonderful. Thank you !. Anything I could
contribute would be delighted.

My Jinja2 is version 2.9.6

I will review the link that you recommend to me.

Thanks again,

>>> import jinja2

>>> jinja2.__version__

'2.9.6'

>>>


*A. J. Alvarez-Socorro*
PhD Student at University of Chile
Faculty of Physical and Mathematical Sciences - Department of Physics




2018-03-10 16:16 GMT+01:00 Gerrit Ansmann <notifications@github.com>:

**Comment by Wrzlprmft** [comment]
Did you try removing the offending line (line 128 from `jitced_template.c`)?

**Comment by Wrzlprmft** [comment]
In yesterday’s release, I removed the offending Unicode characters. Now whoever reads that comment has to live with puny ASCII quotation marks and apostrophes, but your problem should be solved.

Can you please update and check?

**Comment by ajalvarez** [comment]
Yes, I will update the library in few seconds :-)

Thanks for all.


*A. J. Alvarez-Socorro*
PhD Student at University of Chile
Faculty of Physical and Mathematical Sciences - Department of Physics




2018-03-14 7:54 GMT+01:00 Gerrit Ansmann <notifications@github.com>:

**Comment by Wrzlprmft** [comment]
@ajalvarez Are your problems solved now?

**Comment by ajalvarez** [comment]
Yes, thanks.
