### ISSUE TITLE
Possible to make a release and upload to PyPI?

### ISSUE THREAD

**Issue by jajcayn** [neurophysik/jitcdde#29]
Dear developer,

is it possible to make a release containing the newest addition to `jitcdde`, that would be the callbacks? We are using `jitcdde` as the main integrator in modular part of the [`neurolib`](https://github.com/neurolib-dev/neurolib) package (which is a package for computational neuroscience) and we would love to put jitcdde into our requirements, but ideally from PyPI... since we depend on callbacks, right now we must install the master version directly from GitHub and this doesn't play nicely if we wanna do the release and upload `neurolib` to PyPI.

Thanks for considering,
Best,

Nikola

**Comment by Wrzlprmft** [comment]
Sure, I am familiar with that kind of problem. I will see to it as soon as possible. Should take a few days at worst.

**Comment by Wrzlprmft** [comment]
Version 1.7.0 of JiTCDDE has been released and is the first to support callbacks.
