### ISSUE TITLE
How do I use non-symbolic functions?

### ISSUE THREAD

**Issue by saurabhmalani1994** [neurophysik/jitcdde#31]
Is there any way to use JITCDDE for DDEs that cannot be expressed symbolically? I am training a neural network using Tensorflow+Keras to learn a DDE, and I want to use a DDE solver to numerically integrate this learned DDE. However, Tensorflow+Keras can not take in symbolic inputs.

**Comment by Wrzlprmft** [comment]
Yes, you can use the callback functionality. Search [the documentation](https://jitcdde.readthedocs.io/en/latest/#the-main-class) for `callback` to read about it. Briefly, it allows you to call a Python function within the derivative. You may need to write a wrapper to make it fit the format.

Be aware that this may be horribly inefficient (as well as it may be not) and it may be worth trying to find a way to export your learned solution in symbolic form. You also may want to look at [this issue](https://github.com/neurophysik/jitcxde_common/issues/1).
