### ISSUE TITLE
Running mackey_glass_lyap.py causes Python crash

### ISSUE THREAD

**Issue by hangyao** [neurophysik/jitcdde#4]
Running *mackey_glass_lyap.py* in *examples* folder causes Python crash.
*mackey_glass.py* is running okay.

Here is the output:
```
(python3) C:\Users\cyao\Documents\Python\jitcdde\examples>python mackey_glass_ly
ap.py
Generating, compiling, and loading C code.
jitced.c
C:\Users\cyao\AppData\Local\Temp\tmpvmly19ga\jitced.c(706): warning C4244: 'init
ializing': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data

   Creating library C:\Users\cyao\AppData\Local\Temp\tmpvmly19ga\Release\Users\c
yao\AppData\Local\Temp\tmpvmly19ga\jitced.cp36-win_amd64.lib and object C:\Users
\cyao\AppData\Local\Temp\tmpvmly19ga\Release\Users\cyao\AppData\Local\Temp\tmpvm
ly19ga\jitced.cp36-win_amd64.exp
Generating code
Finished generating code
Using default integration parameters.
```

Using Python 3.6, Windows 7, and VC++ Build Tool 14.0

**Comment by Wrzlprmft** [comment]
Thanks for your report. I will not get to a Windows machine before Monday, but until then can you please tell me:

* Does `mackey_glass.py` also produce the conversion warning?
* How exactly does it crash? Is there any message?
* Can you find out at which exact step the program crashes?

**Comment by hangyao** [comment]
Thank you for your prompt response! To answer your questions:
1. No. ```mackey_glass.py``` doesn't produce the conversion warning.
2. In Windows, it prompts ```Python has stopped working...``` and then asks for sending the error information to MS. Here is the Windows error information metadata attached. Hopefully it will help.
3. It crashes at line 33: ```DDE.step_on_discontinuities(max_step=1.0)```

[WERBCB3.tmp.WERInternalMetadata.txt](https://github.com/neurophysik/jitcdde/files/1166182/WERBCB3.tmp.WERInternalMetadata.txt)

**Comment by Wrzlprmft** [comment]
This should be fixed now. Thanks again for spotting.
