### ISSUE TITLE
Solving delay differential equation with variable delay using Jitcdde

### ISSUE THREAD

**Issue by alvarojh123** [neurophysik/jitcdde#48]
HI,
I saw many tutorials to learn how to use Jitcdde, but many of them use constant delays. I want to know if is possible to solve variable delay using Jitcdde. Something like this

$$
dy/ dt =  y(t) \times ( G(t + \tau) - G(t)) 
$$

$$
d\tau/ dt = F(t) / F(t + d\tau) 
$$

Where G and F are functions. For exemplification both could be a $sin$

Please @Wrzlprmft  could you give an example of how to implement this type of delay equations using JITCDDE.

**Comment by Wrzlprmft** [comment]
Brief answer: Yes, this is possible and the implementation is mostly straightforward. You just write something like `G(t+y(1))`, where `y(1)` is the dynamical variable representing *τ.* [Here](https://jitcdde.readthedocs.io/en/stable/#time-and-state-dependent-delays) is a brief documentation and also a link to an example.

Note that I am not exactly sure what *dτ* represents in your equations, so I cannot comment on that.
