### ISSUE TITLE
clang: error: the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by drsaroj** [neurophysik/jitcdde#49]
Hello,

I am getting this error on running the jitcdde

clang: error: the clang compiler does not support '-march=native'
error: command '/usr/bin/clang' failed with exit code 1

I am using the version jitcxde-common 1.5.4

**Comment by Wrzlprmft** [comment]
Let me guess: You are on an Apple machine using the Clang that comes with it.

Either way you need to make JiTCDDE not use that Clang with that flag, for which there are several options:

* Use no Clang at all, but e.g., GCC. See [this](https://jitcde-common.readthedocs.io/en/latest/#choosing-the-compiler) for more information.

* Install a different version of Clang that supports the flag. If my initial guess was correct, see [this](https://stackoverflow.com/q/43555410/2127008) and [this](https://stackoverflow.com/q/65966969/2127008) SO question for more information.

* Make JiTCDDE not use the flag as follows:

  ``` Python 3
  from jitcxde_common import DEFAULT_COMPILE_ARGS
  DEFAULT_COMPILE_ARGS.remove("-march=native")
  DDE = jitcdde(…)
  DDE.compile_C( extra_compile_args=DEFAULT_COMPILE_ARGS, verbose=True ) 
  ```
  `verbose=True` is only so you can check the result. You might need to remove `-mtune=native` as well. If my initial guess was correct, you can also add a system-specific flag for optimisation as per [this SO post](https://stackoverflow.com/q/65966969/2127008).
