### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by alexfikl** [neurophysik/jitcdde#55]
I'm looking at this project for some simulations (networks of a few hundred Wilson-Cowan neurons) and was wondering what the state of it is.

Is it still maintained? Would you accept some PRs to modernize the code a bit? I'm thinking
* Adding a CI with Github Actions.
* Switching to `pyproject.toml` instead of `setup.py`.
* Adding some linting (preferably [ruff](https://github.com/astral-sh/ruff)).
* If time permits, it would be great to also add type annotations.

**Comment by Wrzlprmft** [comment]
Yes, I still maintain this. To be a bit more precise: If you find any bugs, have feature requests or just need support, I will do my best to help. However, I currently have no plans that go beyond maintenance.

If you want to work on the project yourself, I would welcome this and try to support this. In particular keeping up to date with changes to the Python package ecosystem may be unavoidable. Any other improvements are welcome as well. (Note, however, that I oppose manual line wrapping in text or indenting with spaces – no idea if there is a linter that can be taught to accept these.)

**Comment by alexfikl** [comment]
> Yes, I still maintain this. To be a bit more precise: If you find any bugs, have feature requests or just need support, I will do my best to help. However, I currently have no plans that go beyond maintenance.

Thank you for the quick and thorough answer! That's good to hear. From some preliminary fiddling, this project already does what I would need it to do very well :grin:

> If you want to work on the project yourself, I would welcome this and try to support this. In particular keeping up to date with changes to the Python package ecosystem may be unavoidable. Any other improvements are welcome as well. Note, however, that I oppose manual line wrapping in text or indenting with spaces – no idea if there is a linter that can be taught to accept these. 

I don't think that's a problem. At least `ruff` (and `flake8`) has specific error codes for those errors which can be disabled globally in the project. However, if you have specific formatting you want to encourage, it's probably not my place to add linting.

> Also, all sister modules (JiTCODE, JiTCSDE, CHSPy) should be treated equally (e.g., when upgrading to a new packaging system).

I'll keep that in mind and try to propose changes across all the packages.

**Comment by Wrzlprmft** [comment]
> However, if you have specific formatting you want to encourage, it's probably not my place to add linting.

I don’t have a specific formatting preference, except for the two points mentioned.
