### ISSUE TITLE
error when setting max_delay 

### ISSUE THREAD

**Issue by LukeLabrie** [neurophysik/jitcdde#56]
My kernel crashes with a seg fault if I set a max delay that is lower than the total integration time. For context, I have a system with several input-dependent delays, as well as several different delays. I am therefore trying to use `integrate_blindly` up until the largest delay. I've tried to make a minimal example below, which also includes the input-dependent delay of the form I am using. 

```python
from jitcdde import jitcdde_input, input, y, t
import numpy as np 
from chspy import CubicHermiteSpline

# parameters
tau_0 = 10.0
t_event = 50.0
base_flow_fraction = 0.5
W_0 = 25.0                  # kg/s
lambda_flow = 10.0          # kg/s
V_f = 1.0                   # m^3
rho_f = 1000.0              # kg/m^3
m_f = V_f*rho_f             # kg
Q_in = 1.0                  # MW
Q_out = 1.0                 # MW
scp_f = 1.5e-3              # MW/deg C
T_0 = 50                    # deg C

# domain
T = np.arange(0,1000,0.01)

# flow input
W = input(0)
def flow_event(t):
    if t < t_event:
        return W_0
    else:
        return max(W_0*np.exp(-(t-t_event)/lambda_flow), W_0*base_flow_fraction)
flow_spline = CubicHermiteSpline(n = 1)
flow_spline.from_function(flow_event, times_of_interest = T)

# flow-dependent delay
tau_adj = tau_0*W/W_0

# define system
f = [
    (W/m_f)*(y(1,t-tau_adj)-y(0)) + Q_in/(m_f*scp_f),
    (W/m_f)*(y(0,t-tau_adj)-y(1)) - Q_out/(m_f*scp_f)
]

DDE = jitcdde_input(f, flow_spline)
DDE.constant_past([T_0,T_0])
DDE.max_delay = tau_0/base_flow_fraction

sol = []
for t_x in T:
    sol.append(DDE.integrate(t_x))
```

This system describes a highly simplified thermal flow model between two well-mixed tanks, with an advective term dependent on the other tank's temperature with some delay, and an arbitrarily chosen input and removal term. At `t = 50.0`, the flow decays exponentially to 50% of its original value. Consequently, the delay should increase to  $\tau_{new} = \tau_{old}*(W_{old}/W_{new}) = \tau_{old}*W_{old}/(0.5 \times W_{old}) = \tau_{old}/0.5 $. Setting this as the `max_delay ` leads to a seg fault and the python kernel dying. Looks to me like it's happening at the compilation step. Through trial and error, I've noticed that the integration only goes well if the max delay is greater than the total integration time. 

Perhaps there is an issue in my implementation. For context,  I am implementing some PID control modeling on my system using `jitcdde`'s callback functions (as the input needs to be updated with each integration step). I've noticed that the discontinuity handling can throw off the derivative estimates at the start of the integration. I can't use `step_on_discontinuities` because this is not yet supported on `jitcdde_input`. So I'd like to use `integrate_blindly`. This is when I started running into this issue. 

If relevant, I'm using version `1.8.1`.

**Comment by Wrzlprmft** [comment]
Very quickly:

There is something missing in the setter of `max_delay` for `jitcdde_input`. I will fix this soon.

Until then, a solution in many contexts is to set the `max_delay` directly in the constructor (instead of `DDE.max_delay = …`):

``` Python3
DDE = jitcdde_input(f, flow_spline,max_delay=tau_0/base_flow_fraction)
```

If this is not feasible in your actual application, ensure manually that the `max_delay` is at least your input duration. This is what should happen under the hood, but doesn’t.

**Comment by Wrzlprmft** [comment]
> What exactly do you mean by input duration? In the above example, the input only starts changing after a certain time, but still a spline is defined at all times. Would the input duration refer to just the time after it starts changing? Or all times where the spline is defined?

Where it is defined (which is usually the integration time).

**Comment by LukeLabrie** [comment]
> If this is not feasible in your actual application, ensure manually that the `max_delay` is at least your input duration. This is what should happen under the hood, but doesn’t.

Are you saying that this should but doesn't happen under the hood when called in the constructor? Or were you referring to the setter not working? 

 > Where it is defined (which is usually the integration time).

Ok, if the max_delay needs to be at least the input duration, wouldn't that imply that you need to use fixed-step integration any time there is input?

**Comment by Wrzlprmft** [comment]
> > If this is not feasible in your actual application, ensure manually that the `max_delay` is at least your input duration. This is what should happen under the hood, but doesn’t.
> 
> Are you saying that this should but doesn't happen under the hood when called in the constructor? Or were you referring to the setter not working?

I am referring to the setter. The constructor does everything it should when handling its `max_delay` argument, but the setter for the attribute `max_delay` (which is what is called when you do something like `DDE.max_delay = …`) doesn’t.

> > Where it is defined (which is usually the integration time).
> 
> Ok, if the max_delay needs to be at least the input duration, wouldn't that imply that you need to use fixed-step integration any time there is input?

I fail to see why. Mind that integration and sampling steps are generally distinct for modern integration methods. Also, delayed calls do not need to fall on integration steps for the method JiTCDDE is using, since it interpolates.

**Comment by LukeLabrie** [comment]
> I fail to see why.

My understanding is that `integrate_blindly` uses a fixed step. And if this needs to be used up to the max_delay to avoid the discontinuity issue, then if you have input for all integration time, you would need to use `integrate_blindly` for all integration time, no?

**Comment by Wrzlprmft** [comment]
> > I fail to see why.
> 
> My understanding is that `integrate_blindly` uses a fixed step. And if this needs to be used up to the max_delay to avoid the discontinuity issue, then if you have input for all integration time, you would need to use `integrate_blindly` for all integration time, no?

Ah, I see. I would have to check the code again, but you are probably right. However, there is a third method to handle initial discontinuities, `adjust_diff`, which should work (but I haven’t tested it).
