### ISSUE TITLE
Integration issue and Hopf bifurcation question

### ISSUE THREAD

**Issue by hangyao** [neurophysik/jitcdde#6]
Hi @Wrzlprmft ,

I continue my attempt to apply Jitcdde. Now I encounter a new issue that puzzles me. I'm trying to solve a DDE system. The system contains two equations and three discrete delays; and nine other parameters. With a set of parameter values, Jitcdde does solve the equation. However, with another of the parameter values, Jitcdde does not. My system is well-posted, that is, the right-hand side of the system is continuously differentiable and thus the solution with continuous initial conditions must exist and unique. Can you point me a direction to solve this issue?

Here is another issue I encountered. With the set of good parameter values that can solve the equation, increasing a delay parameter value does not produce a Hopf bifurcation. By theory and also our theoretical proof, when this delay increases, a Hopf bifurcation should occur for this system. Maybe I used the package incorrectly. Can you let me know to use Jitcdde, what else I should install or whatsoever?

Thank you very much!

Hang

**Comment by Wrzlprmft** [comment]
Without any specific details on your DDEs or even an error message, I cannot possibly help you.
